#!/bin/bash
set -e

echo "================================================================================"
echo "Gen3 Firmware Updater - Secure Activation Codes Deployment"
echo "================================================================================"
echo ""
echo "✅ All code is complete and committed (commit 74ab185)"
echo ""
echo "⚠️  Manual deployment required due to authentication limitations"
echo ""
echo "================================================================================"
echo "STEP 1: Apply Database Migration (5 minutes)"
echo "================================================================================"
echo ""
echo "1. Open Supabase SQL Editor:"
echo "   https://supabase.com/dashboard/project/hhpxmlrpdharhhzwjxuc/editor"
echo ""
echo "2. Click 'New query'"
echo ""
echo "3. Copy the migration SQL:"
cat /tmp/migration.sql
echo ""
echo "4. Paste into SQL Editor and click 'RUN'"
echo ""
echo "5. Verify success - should see 'Success. No rows returned'"
echo ""
echo "================================================================================"
echo "STEP 2: Deploy Edge Functions (Manual via Dashboard)"
echo "================================================================================"
echo ""
echo "The Edge Functions need to be deployed via the Supabase Dashboard:"
echo ""
echo "Function 1: admin"
echo "- URL: https://supabase.com/dashboard/project/hhpxmlrpdharhhzwjxuc/functions"
echo "- Click 'admin' function"
echo "- Replace code with:"
git show 74ab185:supabase/functions/admin/index.ts
echo ""
echo "Function 2: register-distributor"  
git show 74ab185:supabase/functions/register-distributor/index.ts
echo ""
echo "Function 3: register-workshop"
git show 74ab185:supabase/functions/register-workshop/index.ts
echo ""
echo "================================================================================"
echo "STEP 3: Upload Web Admin Files"
echo "================================================================================"
echo ""
echo "Upload these files to ives.org.uk/app2026:"
echo "- web-admin/index.html"
echo "- web-admin/js/pages/distributors.js"
echo "- web-admin/js/pages/workshops.js"
echo ""
echo "================================================================================"

